# Site settings
name: Joe Torreggiani
email: joetorreggiani@gmail.com
tag_line: I'm on a mission to do the most good I can do.
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, JavaScript, Ruby, Startups, Agile, Software Testing"
skills: "Technologist | Educator | Activist"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joetorreggiani/
  - title: medium
    url: https://medium.com/@jtorreggiani
  - title: twitter
    url: https://twitter.com/joetorreggiani
  - title: github
    url: https://github/jtorreggiani

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 487eb0
  primary-rgb: "33, 150, 243"
  secondary: 2f3640
  secondary-dark: 353b48
  section-tout: dcdde1

# Build settings
markdown: kramdown
permalink: pretty
